### ISSUE TITLE
Color scheme for activities not defined

### ISSUE THREAD

**Issue by psane** [pallavi05g/si699-socialize#3]
- Local Tours - #A8C8DA
- Adventure - #FA9FA4
- Food - #FCD049
- Camping - #F3EA94
- Trekking - #CAE4D3
- Movies - #F07077
- Sports - #B3DFF5
- Suggested
- All
- Popular
- Near Me
- Expiring

**Comment by psane** [comment]
@xxlingz can you add the hex code for each activity type here, based on the color palette you decided.
Or you can directly add it to the CSS classes for these activities.

**Comment by xxlingz** [comment]
@psane @pallavi05g Color scheme hex changed! I'll update the hex on the actual css file

**Comment by xxlingz** [comment]
@psane @pallavi05g css hex updated. Issue closed.
